version: "3.7"
services:
  cli:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    init: true
    user: node
    working_dir: /home/node/app
    entrypoint: npm
    command: start
    volumes:
      - .:/home/node/app
      - npm-cache:/home/node/.npm

volumes:
  npm-cache:
    external: false
